In [5]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df=pd.read_csv("Prestige_miss.csv")
df

     education   income  women  prestige  census  type
0        13.11  12351.0  11.16      68.8  1113.0  prof
1        12.26  25879.0   4.02      69.1  1130.0  prof
2        12.77   9271.0  15.70      63.4  1171.0  prof
3        11.42      NaN   9.11      56.8  1175.0  prof
4        14.62   8403.0  11.68      73.5  2111.0  prof
5        15.64  11030.0   5.13      77.6  2113.0   NaN
6        15.09   8258.0  25.65      72.6  2133.0  prof
7          NaN  14163.0   2.69      78.1  2141.0  prof
8        14.52  11377.0   1.03      73.1  2143.0  prof
9        14.64  11023.0   0.94      68.8  2153.0  prof
10       12.39      NaN   1.91      62.0  2161.0  prof
11         NaN   7059.0   7.83      60.0  2163.0  prof
12       13.83   8425.0  15.33      53.8  2183.0  prof
13       14.44   8049.0  57.31      62.2  2311.0  prof
14       14.36   7405.0  48.28      74.9  2315.0  prof
15       14.21   6336.0  54.77      55.1  2331.0  prof
16       15.77  19263.0   5.13      82.3  2343.0  prof
17       14.15   6112.0  77.10       NaN  2351.0  prof
18       15.22   9593.0  34.89      58.3  2391.0  prof
19       14.50   4686.0   4.14      72.8  2511.0  prof
20       15.97  12480.0  19.59      84.6  2711.0  prof
21       13.62   5648.0  83.78      59.6     NaN  prof
22       15.08   8034.0  46.80      66.1  2733.0  prof
23       15.96  25308.0  10.56      87.2  3111.0  prof
24       15.94  14558.0   4.32      66.7  3115.0  prof
25       14.71  17498.0   6.91      68.4  3117.0  prof
26       12.46   4614.0  96.12      64.7  3131.0  prof
27        9.45   3485.0  76.14      34.9     NaN    bc
28       13.62   5092.0  82.66      72.1  3137.0  prof
29       15.21  10432.0  24.71      69.3  3151.0  prof
..         ...      ...    ...       ...     ...   ...
72        7.42   1890.0  72.24      23.2  8221.0    bc
73        6.69   4443.0  31.36      33.3  8267.0    bc
74        6.74   3485.0  39.48      28.8  8278.0    bc
75       10.09   8043.0   1.50      42.5  8311.0    bc
76        8.81   6686.0   4.28      44.2  8313.0    bc
77        8.40   6565.0   2.30      35.9  8333.0    bc
78        7.92   6477.0   5.17      41.8  8335.0    bc
79        8.43   5811.0  13.62      35.9  8513.0    bc
80        8.78   6573.0   5.78      43.7  8515.0    bc
81        8.76   3942.0  74.54      50.8  8534.0    bc
82       10.29   5449.0   2.92      37.2  8537.0    bc
83        6.38   2847.0  90.67      28.2     NaN    bc
84        8.10   5795.0    NaN      38.1  8581.0    bc
85       10.10   7716.0   0.78      50.3  8582.0    bc
86        6.67   4696.0   0.00      27.3  8715.0    bc
87        9.05   8316.0   1.34      40.9  8731.0    bc
88        9.93   7147.0   0.99      50.2  8733.0    bc
89        8.24   8880.0   0.65      51.1  8780.0    bc
90        6.92   5299.0   0.56      38.9  8781.0    bc
91        6.60   5959.0   0.52      36.2  8782.0    bc
92        7.81   4549.0   2.46      29.9  8785.0    bc
93        8.33   6928.0   0.61      42.9  8791.0    bc
94        7.52   3910.0   1.09      26.5  8798.0    bc
95       12.27  14032.0   0.58      66.1  9111.0  prof
96        8.49      NaN   0.00      48.9  9131.0    bc
97        7.58   5562.0   9.47      35.9  9171.0    bc
98        7.93   4224.0    NaN      25.1  9173.0    bc
99        8.37   4753.0   0.00      26.1  9313.0    bc
100      10.00   6462.0  13.58      42.2  9511.0    bc
101       8.55   3617.0  70.87      35.2  9517.0    bc

[102 rows x 6 columns]

In [8]:
mask1=df["education"].isnull()
mask2=df["income"].isnull()
mask3=df["women"].isnull()
mask4=df["prestige"].isnull()
mask5=df["census"].isnull()
mask6=df["type"].isnull()

In [9]:

df2=df.copy()

In [10]:
df2.dropna(axis=0,inplace=True)

In [11]:
df2

     education   income  women  prestige  census  type
0        13.11  12351.0  11.16      68.8  1113.0  prof
1        12.26  25879.0   4.02      69.1  1130.0  prof
2        12.77   9271.0  15.70      63.4  1171.0  prof
4        14.62   8403.0  11.68      73.5  2111.0  prof
6        15.09   8258.0  25.65      72.6  2133.0  prof
8        14.52  11377.0   1.03      73.1  2143.0  prof
9        14.64  11023.0   0.94      68.8  2153.0  prof
12       13.83   8425.0  15.33      53.8  2183.0  prof
13       14.44   8049.0  57.31      62.2  2311.0  prof
14       14.36   7405.0  48.28      74.9  2315.0  prof
15       14.21   6336.0  54.77      55.1  2331.0  prof
16       15.77  19263.0   5.13      82.3  2343.0  prof
18       15.22   9593.0  34.89      58.3  2391.0  prof
19       14.50   4686.0   4.14      72.8  2511.0  prof
20       15.97  12480.0  19.59      84.6  2711.0  prof
22       15.08   8034.0  46.80      66.1  2733.0  prof
23       15.96  25308.0  10.56      87.2  3111.0  prof
24       15.94  14558.0   4.32      66.7  3115.0  prof
25       14.71  17498.0   6.91      68.4  3117.0  prof
26       12.46   4614.0  96.12      64.7  3131.0  prof
28       13.62   5092.0  82.66      72.1  3137.0  prof
29       15.21  10432.0  24.71      69.3  3151.0  prof
34       11.59   4036.0  97.51      46.0  4111.0    wc
36       11.32   4348.0  68.24      49.4  4131.0    wc
38       11.36   4330.0  75.92      47.7  4143.0    wc
39        9.17   4761.0  11.37      30.9  4153.0    wc
40       12.09   3016.0  83.19      32.7  4161.0    wc
47       11.43   6259.0  39.17      35.7  4193.0    wc
48       11.00   4075.0  63.23      35.6  4197.0    wc
49        9.84   7482.0  17.04      41.5  5130.0    wc
..         ...      ...    ...       ...     ...   ...
64        7.11   3472.0  33.57      17.3  6191.0    bc
69        7.54   4199.0  33.30      38.9  8213.0    bc
70        7.64   5134.0  17.26      25.2  8215.0    bc
71        7.64   5134.0  17.26      34.8  8215.0    bc
72        7.42   1890.0  72.24      23.2  8221.0    bc
73        6.69   4443.0  31.36      33.3  8267.0    bc
74        6.74   3485.0  39.48      28.8  8278.0    bc
75       10.09   8043.0   1.50      42.5  8311.0    bc
76        8.81   6686.0   4.28      44.2  8313.0    bc
77        8.40   6565.0   2.30      35.9  8333.0    bc
78        7.92   6477.0   5.17      41.8  8335.0    bc
79        8.43   5811.0  13.62      35.9  8513.0    bc
80        8.78   6573.0   5.78      43.7  8515.0    bc
81        8.76   3942.0  74.54      50.8  8534.0    bc
82       10.29   5449.0   2.92      37.2  8537.0    bc
85       10.10   7716.0   0.78      50.3  8582.0    bc
86        6.67   4696.0   0.00      27.3  8715.0    bc
87        9.05   8316.0   1.34      40.9  8731.0    bc
88        9.93   7147.0   0.99      50.2  8733.0    bc
89        8.24   8880.0   0.65      51.1  8780.0    bc
90        6.92   5299.0   0.56      38.9  8781.0    bc
91        6.60   5959.0   0.52      36.2  8782.0    bc
92        7.81   4549.0   2.46      29.9  8785.0    bc
93        8.33   6928.0   0.61      42.9  8791.0    bc
94        7.52   3910.0   1.09      26.5  8798.0    bc
95       12.27  14032.0   0.58      66.1  9111.0  prof
97        7.58   5562.0   9.47      35.9  9171.0    bc
99        8.37   4753.0   0.00      26.1  9313.0    bc
100      10.00   6462.0  13.58      42.2  9511.0    bc
101       8.55   3617.0  70.87      35.2  9517.0    bc

[69 rows x 6 columns]

    education   income  women  prestige  census  type
3       11.42      NaN   9.11      56.8  1175.0  prof
5       15.64  11030.0   5.13      77.6  2113.0   NaN
7         NaN  14163.0   2.69      78.1  2141.0  prof
10      12.39      NaN   1.91      62.0  2161.0  prof
11        NaN   7059.0   7.83      60.0  2163.0  prof
17      14.15   6112.0  77.10       NaN  2351.0  prof
21      13.62   5648.0  83.78      59.6     NaN  prof
27       9.45   3485.0  76.14      34.9     NaN    bc
30        NaN   5180.0  76.04      67.5  3156.0    wc
31      11.09   6197.0    NaN      57.2  3314.0  prof
32      12.71   7562.0  11.15       NaN  3337.0    wc
33      11.44   8206.0   8.13      54.1  3373.0   NaN
35      11.49   3148.0  95.97      41.9     NaN    wc
37        NaN   2448.0  91.76      42.3  4133.0    wc
41      11.04   2901.0  92.86      38.7     NaN    wc
42       9.22      NaN   7.62      36.1  4172.0    wc
43      10.07   3739.0    NaN      37.2  4173.0    wc
44      10.51   3161.0  96.14      38.1  4175.0   NaN
45      11.20   4741.0    NaN      29.4  4191.0    wc
46      11.13      NaN  56.10      51.1  4192.0    wc
52       9.62    918.0   7.00       NaN  5143.0   NaN
54      11.60   8131.0  13.09      47.3  5171.0   NaN
59        NaN   3116.0  52.00      29.7  6121.0    bc
60       8.50   3930.0    NaN      20.2  6123.0    bc
62       9.46    611.0  96.53      25.9  6147.0   NaN
65        NaN   3582.0  30.08      20.1  6193.0    bc
66       6.84   3643.0   3.60      44.1  7112.0   NaN
67        NaN   1656.0  27.75      21.5  7182.0    bc
68       8.88   6860.0   0.00      35.3  7711.0   NaN
83       6.38   2847.0  90.67      28.2     NaN    bc
84       8.10   5795.0    NaN      38.1  8581.0    bc
96       8.49      NaN   0.00      48.9  9131.0    bc
98       7.93   4224.0    NaN      25.1  9173.0    bc

## For finding missing values of "prestige"

In [130]:
X=df2.iloc[:,[0,1,2,4]]
Y=df2.iloc[:,3]
X_Test=df[mask4].iloc[:,[0,1,2,4]]

In [131]:
import numpy as np
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [132]:
reg.predict(X_Test)

array([60.29292624, 55.32573672, 34.34609921])

In [133]:
df.at[17, 'prestige']=60.2929
df.at[32, 'prestige']=55.3257
df.at[52, 'prestige']=34.3460

In [134]:
mask4=df["prestige"].isnull()
df[mask4]
df

     education   income  women  prestige  census  type
0        13.11  12351.0  11.16   68.8000  1113.0  prof
1        12.26  25879.0   4.02   69.1000  1130.0  prof
2        12.77   9271.0  15.70   63.4000  1171.0  prof
3        11.42      NaN   9.11   56.8000  1175.0  prof
4        14.62   8403.0  11.68   73.5000  2111.0  prof
5        15.64  11030.0   5.13   77.6000  2113.0   NaN
6        15.09   8258.0  25.65   72.6000  2133.0  prof
7          NaN  14163.0   2.69   78.1000  2141.0  prof
8        14.52  11377.0   1.03   73.1000  2143.0  prof
9        14.64  11023.0   0.94   68.8000  2153.0  prof
10       12.39      NaN   1.91   62.0000  2161.0  prof
11         NaN   7059.0   7.83   60.0000  2163.0  prof
12       13.83   8425.0  15.33   53.8000  2183.0  prof
13       14.44   8049.0  57.31   62.2000  2311.0  prof
14       14.36   7405.0  48.28   74.9000  2315.0  prof
15       14.21   6336.0  54.77   55.1000  2331.0  prof
16       15.77  19263.0   5.13   82.3000  2343.0  prof
17       14.15   6112.0  77.10   60.2929  2351.0  prof
18       15.22   9593.0  34.89   58.3000  2391.0  prof
19       14.50   4686.0   4.14   72.8000  2511.0  prof
20       15.97  12480.0  19.59   84.6000  2711.0  prof
21       13.62   5648.0  83.78   59.6000     NaN  prof
22       15.08   8034.0  46.80   66.1000  2733.0  prof
23       15.96  25308.0  10.56   87.2000  3111.0  prof
24       15.94  14558.0   4.32   66.7000  3115.0  prof
25       14.71  17498.0   6.91   68.4000  3117.0  prof
26       12.46   4614.0  96.12   64.7000  3131.0  prof
27        9.45   3485.0  76.14   34.9000     NaN    bc
28       13.62   5092.0  82.66   72.1000  3137.0  prof
29       15.21  10432.0  24.71   69.3000  3151.0  prof
..         ...      ...    ...       ...     ...   ...
72        7.42   1890.0  72.24   23.2000  8221.0    bc
73        6.69   4443.0  31.36   33.3000  8267.0    bc
74        6.74   3485.0  39.48   28.8000  8278.0    bc
75       10.09   8043.0   1.50   42.5000  8311.0    bc
76        8.81   6686.0   4.28   44.2000  8313.0    bc
77        8.40   6565.0   2.30   35.9000  8333.0    bc
78        7.92   6477.0   5.17   41.8000  8335.0    bc
79        8.43   5811.0  13.62   35.9000  8513.0    bc
80        8.78   6573.0   5.78   43.7000  8515.0    bc
81        8.76   3942.0  74.54   50.8000  8534.0    bc
82       10.29   5449.0   2.92   37.2000  8537.0    bc
83        6.38   2847.0  90.67   28.2000     NaN    bc
84        8.10   5795.0    NaN   38.1000  8581.0    bc
85       10.10   7716.0   0.78   50.3000  8582.0    bc
86        6.67   4696.0   0.00   27.3000  8715.0    bc
87        9.05   8316.0   1.34   40.9000  8731.0    bc
88        9.93   7147.0   0.99   50.2000  8733.0    bc
89        8.24   8880.0   0.65   51.1000  8780.0    bc
90        6.92   5299.0   0.56   38.9000  8781.0    bc
91        6.60   5959.0   0.52   36.2000  8782.0    bc
92        7.81   4549.0   2.46   29.9000  8785.0    bc
93        8.33   6928.0   0.61   42.9000  8791.0    bc
94        7.52   3910.0   1.09   26.5000  8798.0    bc
95       12.27  14032.0   0.58   66.1000  9111.0  prof
96        8.49      NaN   0.00   48.9000  9131.0    bc
97        7.58   5562.0   9.47   35.9000  9171.0    bc
98        7.93   4224.0    NaN   25.1000  9173.0    bc
99        8.37   4753.0   0.00   26.1000  9313.0    bc
100      10.00   6462.0  13.58   42.2000  9511.0    bc
101       8.55   3617.0  70.87   35.2000  9517.0    bc

[102 rows x 6 columns]

## For findind ,issing values of "income"

In [136]:
df3=df.copy()
df3.dropna(axis=0,inplace=True)
X=df3.iloc[:,[0,2,3,4]]
Y=df3.iloc[:,1]
X_Test=df[mask2].iloc[:,[0,2,3,4]]
import numpy as np
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [139]:
reg.predict(X_Test)

array([10792.21579666, 11807.94068961,  6968.39218727,  6284.8194963 ,
        8491.30669765])

In [142]:
df.at[3, 'income']=10792.21
df.at[10, 'income']=11807.94
df.at[42, 'income']=6968.39
df.at[46, 'income']=6284.81
df.at[96, 'income']=8491.30

## For finding missing values of "women"

In [143]:
df4=df.copy()
df4.dropna(axis=0,inplace=True)
X=df4.iloc[:,[0,1,3,4]]
Y=df4.iloc[:,2]
X_Test=df[mask3].iloc[:,[0,1,3,4]]
import numpy as np
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X, Y)
reg.predict(X_Test)

array([38.81182698, 43.72601499, 41.35431434, 32.5408171 , 15.7618447 ,
       19.68612852])

In [146]:
df.at[31, 'women']=38.81
df.at[43, 'women']=43.72
df.at[45, 'women']=41.35
df.at[60, 'women']=32.54
df.at[84, 'women']=15.76
df.at[98, 'women']=19.68

## Fr finding missing values of "census"

In [148]:
df5=df.copy()
df5.dropna(axis=0,inplace=True)
X=df5.iloc[:,[0,1,2,3]]
Y=df5.iloc[:,4]
X_Test=df[mask5].iloc[:,[0,1,2,3]]
import numpy as np
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X, Y)
reg.predict(X_Test)

array([2469.39584618, 5791.98896661, 3821.20738181, 4199.14267854,
       8244.7875156 ])

In [154]:
df.at[21, 'census']=2469.39
df.at[27, 'census']=5791.98
df.at[35, 'census']=3821.20
df.at[41, 'census']=4199.14
df.at[83, 'census']=8244.78

## For finding missing values of "education"

In [161]:
df6=df.copy()
df6.dropna(axis=0,inplace=True)
X=df6.iloc[:,[1,2,3,4]]
Y=df6.iloc[:,0]
X_Test=df[mask1].iloc[:,[1,2,3,4]]
import numpy as np
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X, Y)
reg.predict(X_Test)

array([15.09677414, 13.46499177, 13.86668649, 11.13202114,  8.92824977,
        7.95146229,  7.61780049])

In [162]:
df.at[7, 'education']=15.09
df.at[11, 'education']=13.46
df.at[30, 'education']=13.86
df.at[37, 'education']=11.13
df.at[59, 'education']=8.92
df.at[65, 'education']=7.95
df.at[67, 'education']=7.61

## For finding missing values of "type"

In [167]:
df7=df.copy()
df7.dropna(axis=0,inplace=True)
X=df7.iloc[:,[0,1,2,3,4]]
Y=df7.iloc[:,5]
X_Test=df[mask6].iloc[:,[0,1,2,3,4]]
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier() 
classifier=classifier.fit(X, Y) 
classifier.predict(X_Test)

array(['prof', 'wc', 'wc', 'wc', 'wc', 'bc', 'bc', 'bc'], dtype=object)

In [169]:
df.at[5, 'type']='prof'
df.at[33, 'type']='wc'
df.at[44, 'type']='wc'
df.at[52, 'type']='wc'
df.at[54, 'type']='wc'
df.at[62, 'type']='bc'
df.at[66, 'type']='bc'
df.at[68, 'type']='bc'

In [174]:
df

     education    income  women  prestige   census  type
0        13.11  12351.00  11.16   68.8000  1113.00  prof
1        12.26  25879.00   4.02   69.1000  1130.00  prof
2        12.77   9271.00  15.70   63.4000  1171.00  prof
3        11.42  10792.21   9.11   56.8000  1175.00  prof
4        14.62   8403.00  11.68   73.5000  2111.00  prof
5        15.64  11030.00   5.13   77.6000  2113.00  prof
6        15.09   8258.00  25.65   72.6000  2133.00  prof
7        15.09  14163.00   2.69   78.1000  2141.00  prof
8        14.52  11377.00   1.03   73.1000  2143.00  prof
9        14.64  11023.00   0.94   68.8000  2153.00  prof
10       12.39  11807.94   1.91   62.0000  2161.00  prof
11       13.46   7059.00   7.83   60.0000  2163.00  prof
12       13.83   8425.00  15.33   53.8000  2183.00  prof
13       14.44   8049.00  57.31   62.2000  2311.00  prof
14       14.36   7405.00  48.28   74.9000  2315.00  prof
15       14.21   6336.00  54.77   55.1000  2331.00  prof
16       15.77  19263.00   5.13   82.3000  2343.00  prof
17       14.15   6112.00  77.10   60.2929  2351.00  prof
18       15.22   9593.00  34.89   58.3000  2391.00  prof
19       14.50   4686.00   4.14   72.8000  2511.00  prof
20       15.97  12480.00  19.59   84.6000  2711.00  prof
21       13.62   5648.00  83.78   59.6000  2469.39  prof
22       15.08   8034.00  46.80   66.1000  2733.00  prof
23       15.96  25308.00  10.56   87.2000  3111.00  prof
24       15.94  14558.00   4.32   66.7000  3115.00  prof
25       14.71  17498.00   6.91   68.4000  3117.00  prof
26       12.46   4614.00  96.12   64.7000  3131.00  prof
27        9.45   3485.00  76.14   34.9000  5791.98    bc
28       13.62   5092.00  82.66   72.1000  3137.00  prof
29       15.21  10432.00  24.71   69.3000  3151.00  prof
..         ...       ...    ...       ...      ...   ...
72        7.42   1890.00  72.24   23.2000  8221.00    bc
73        6.69   4443.00  31.36   33.3000  8267.00    bc
74        6.74   3485.00  39.48   28.8000  8278.00    bc
75       10.09   8043.00   1.50   42.5000  8311.00    bc
76        8.81   6686.00   4.28   44.2000  8313.00    bc
77        8.40   6565.00   2.30   35.9000  8333.00    bc
78        7.92   6477.00   5.17   41.8000  8335.00    bc
79        8.43   5811.00  13.62   35.9000  8513.00    bc
80        8.78   6573.00   5.78   43.7000  8515.00    bc
81        8.76   3942.00  74.54   50.8000  8534.00    bc
82       10.29   5449.00   2.92   37.2000  8537.00    bc
83        6.38   2847.00  90.67   28.2000  8244.78    bc
84        8.10   5795.00  15.76   38.1000  8581.00    bc
85       10.10   7716.00   0.78   50.3000  8582.00    bc
86        6.67   4696.00   0.00   27.3000  8715.00    bc
87        9.05   8316.00   1.34   40.9000  8731.00    bc
88        9.93   7147.00   0.99   50.2000  8733.00    bc
89        8.24   8880.00   0.65   51.1000  8780.00    bc
90        6.92   5299.00   0.56   38.9000  8781.00    bc
91        6.60   5959.00   0.52   36.2000  8782.00    bc
92        7.81   4549.00   2.46   29.9000  8785.00    bc
93        8.33   6928.00   0.61   42.9000  8791.00    bc
94        7.52   3910.00   1.09   26.5000  8798.00    bc
95       12.27  14032.00   0.58   66.1000  9111.00  prof
96        8.49   8491.30   0.00   48.9000  9131.00    bc
97        7.58   5562.00   9.47   35.9000  9171.00    bc
98        7.93   4224.00  19.68   25.1000  9173.00    bc
99        8.37   4753.00   0.00   26.1000  9313.00    bc
100      10.00   6462.00  13.58   42.2000  9511.00    bc
101       8.55   3617.00  70.87   35.2000  9517.00    bc

[102 rows x 6 columns]